apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "locust.fullname" . }}-master
  namespace: {{ .Values.master.namespace }}
  labels:
{{ include "locust.labels" . | indent 4 }}
{{- with .Values.master.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
